export type Intent =
  | 'Growth of the Business'
  | 'Expansion into New Markets'
  | 'Expansion of the Team'
  | 'Launch of a New Product'
  | 'Formation of Strategic Partnerships'
  | 'Innovation in the Business'
  | 'Expansion on a Global Scale'
  | 'Collaborations with Other Businesses'
  | 'Investment in Research and Development'
  | 'Implementation of Corporate Social Responsibility Initiatives'
  | 'Public Offering of Shares'
  | 'Mergers and Acquisitions of Companies'
  | 'Rebranding of the Business'
  | 'Adoption of Sustainability Practices'
  | 'Restructuring of the Business'
  | 'Filing for Bankruptcy'
  | 'Liquidation of Assets'
  | 'Formation of Joint Ventures'
  | 'Franchising Opportunities'
  | 'Outsourcing of Tasks'
  | 'Insourcing of Tasks'
  | 'Offshoring of Operations'
  | 'Reshoring of Operations'
  | 'Creation of Spin-offs'
  | 'Diversification of the Business'
  | 'Divestment from Certain Areas'
  | 'Dealing with Legal Issues'
  | 'Compliance with Regulatory Requirements'
  | 'Engagement with Customers'
  | 'Protection of Data Privacy'
  | 'Assurance of Quality'
  | 'Optimization of the Supply Chain'
  | 'Improvement of Operational Efficiency'
  | 'Reduction of Costs'
  | 'Generation of Revenue'
  | 'Increase in Market Share'
  | 'Raising Brand Awareness'
  | 'Promotion of Employee Wellbeing'
  | 'Governance of the Corporation'
  | 'Management of Risks'
  | 'Development towards Sustainability'
  | 'Retention of Customers'
  | 'Delivery of Services'
  | 'Transformation through Digital Means'
  | 'Adoption of Technology'
  | 'Use of Agile Methodologies'
  | 'Training of Employees'
  | 'Use of Advanced Analytics'
  | 'Implementation of Cybersecurity Measures'
  | 'Automation of Processes'
  | 'Integration of Systems'
  | 'Adoption of Cloud Computing'
  | 'Management of Customer Relationships'
  | 'Establishment of Online Presence'
  | 'Recovery from Disasters'
  | 'Investment in Infrastructure'
  | 'Adherence to Corporate Ethics'
  | 'Promotion of Workplace Diversity'
  | 'Governance of Data'
  | 'Centricity towards Customers'
  | 'Marketing through Digital Channels'
  | 'Adoption of Advanced Manufacturing Techniques'
  | 'Cross-selling and Up-selling Strategies'
  | 'Adoption of Lean Management Practices'
  | 'Continuity of the Business'
  | 'Adoption of Renewable Energy Sources'
  | 'Management of Talent'
  | 'Use of Blockchain Technology'
  | 'Use of Virtual and Augmented Reality Technologies'
  | 'Management of Knowledge'
  | 'Adoption of Internet of Things Technologies'
  | 'Security of Information'
  | 'Proactive Corporate Social Responsibility Initiatives'
  | 'Assessment of Risks'
  | 'Data-driven Decision Making'
  | 'Management of Performance'
  | 'Adoption of Green Practices'
  | 'Management of Finances'
  | 'Adoption of a Holistic Business Approach'
  | 'Management of the Supply Chain'
  | 'Use of Predictive Analytics'
  | 'Service to Customers'
  | 'Management of Quality'
  | 'Formation of Strategic Alliances'
  | 'Marketing across Multiple Channels'
  | 'Backup and Recovery of Data'
  | 'Promotion of Employee Wellness'
  | 'Adoption of a Flexible Work Policy'
  | 'Implementation of a CSR Program'
  | 'Adoption of a Zero-waste Policy'
  | 'Provision of Logistics Solutions'
  | 'Acquisition of Talent'
  | 'Adoption of a Mobile-first Approach'
  | 'Engagement in E-commerce'
  | 'Marketing through Content'
  | 'Adoption of Remote Work'
  | 'Use of CRM Software'
  | 'Strategy for Cybersecurity'
  | 'Promotion of a Continuous Learning Culture'
  | 'Use of Automation Technologies'
  | 'Strategy for Digital Transformation'
  | 'Promotion of a Diversity and Inclusion Culture'
  | 'Use of Business Intelligence Tools'
  | 'Management of Change'
  | 'Promotion of a Transparency Culture'
  | 'Use of Project Management Tools'
  | 'Management of Crises'
  | 'Promotion of an Ethical Conduct Culture'
  | 'Marketing through Social Media'
  | 'Strategy for Data Governance'
  | 'Promotion of a Customer Centricity Culture'
  | 'Optimization for Search Engines'
  | 'Strategy for Risk Management'
  | 'Promotion of an Accountability Culture'
  | 'Design of User Experiences'
  | 'Strategy for Cybersecurity'
  | 'Other';

export type IdentificationMethod =
  | 'Latest Funding Round Type or Series'
  | 'Amount Raised in Latest Funding Round (USD)'
  | 'Number of Acquisitions Made'
  | 'Number of Hires Made'
  | 'Job Postings Made by the Company'
  | 'Announcements of New Products'
  | 'Press Releases Issued'
  | 'Announcements of New Partnerships'
  | 'Investments in Research and Development'
  | 'Filings of Patents'
  | 'Openings of New Offices'
  | 'Announcements of Entry into New Markets'
  | 'Announcements of New Collaborations'
  | 'Publications of Research'
  | 'Announcements of Rebranding'
  | 'Announcements of Initial Public Offerings'
  | 'Announcements of Mergers'
  | 'Announcements of Divestitures'
  | 'Legal Documents Issued'
  | 'Announcements of Corporate Social Responsibility Initiatives'
  | 'Announcements of Digital Transformations'
  | 'Reports on Sustainability'
  | 'Announcements of Restructuring'
  | 'Filings of Bankruptcy'
  | 'Notices of Liquidation'
  | 'Announcements of Joint Ventures'
  | 'Opportunities for Franchising'
  | 'Contracts for Outsourcing'
  | 'Announcements of Insourcing'
  | 'Announcements of Offshoring'
  | 'Announcements of Reshoring'
  | 'Announcements of Spin-Offs'
  | 'Launches of New Products'
  | 'Implementation of Cybersecurity Measures'
  | 'Other';

export interface intentItem {
  intent: Intent;
  identificationMethod: IdentificationMethod;
}

export interface report {
  items: intentItem[];
}